apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: spring-basic-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 32000
  type: NodePort